name: AWS Web App Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build the Application
        run: npm run build
    

  deploy_staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region us-east-1

      - name: Deploy to Staging
        run: |
          aws elasticbeanstalk create-application-version --application-name "App" --version-label "staging-$GITHUB_SHA" --source-bundle S3Bucket="s3-bucket-app",S3Key="app.zip"
          aws elasticbeanstalk update-environment --environment-name "App-staging" --version-label "staging-$GITHUB_SHA"

  deploy_production:
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region us-east-1

      - name: Deploy to Production
        run: |
          aws elasticbeanstalk create-application-version --application-name "YourApp" --version-label "production-$GITHUB_SHA" --source-bundle S3Bucket="s3-bucket",S3Key="app.zip"
          aws elasticbeanstalk update-environment --environment-name "YourApp-production" --version-label "production-$GITHUB_SHA"
